backend:
  name: github
  repo: kevmgb/savannah-safaris-v2-site # e.g., "username/savannah-safaris"
  branch: main
  base_url: https://api.github.com
  auth_url: https://api.github.com/authorizations
  app_id: __GITHUB_APP_ID__ # This will be replaced at build time from .env
  auth_scope: repo

# For local development without GitHub auth, use:
# backend:
#   name: git-gateway
#   branch: main

media_folder: public/images/blog
public_folder: /images/blog

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - {
          label: "Cover Image",
          name: "coverImage",
          widget: "image",
          required: false,
        }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
